[config]
	dpp=1
	size_round=80
	padding=[256,128,64,128] # 路線(テキスト除く)から画像端の余白 [上,右,下,左]
	background_color='#223'

	[[config.grid]]
		offset=[0,0]
		size=[100,100]
		color='#fff1'
		width=16
	[[config.grid]]
		offset=[0,0]
		size=[1000,1000]
		color='#fff2'
		width=16

	[config.text]
	[config.text.title]
		value='J鯖サバイバル 路線ネットワーク'
		size=128
		color='#fff'
		anchor=['bottom','left'] # 基準位置 = [ 'top' 'bottom' 'left' 'right' から 1~4つ ]
		margin=[64,64] # 余白 = [ 上下, 左右 ]

	[config.text.station]
		size=64
		color='#fff'
		angle=60
		tategaki=false

	[config.text.line]
		size=96

[[line]]
name='蓮雪線'
color='#6ca'
vert='''
-435 1300 雪越
-435 1330
-405 1360
-325 1360
95 1780
230 1780 蓮窪
395 1780
425 1810
445 1810
455 1820
695 1820
735 1780
805 1780 原津
825 1780
885 1840
1375 1840
1440 1905
1575 1905 井村屋
1590 1905
1700 2015
1860 2015 桜台
'''

[[line]]
name='M支線'
color='#6ca'
vert='''
-305 1940 M
-65 1940
-55 1930
-55 1920
-45 1910
15 1910
145 1780
230 1780 蓮窪
'''

[[line]]
name='草原線'
color='#473'
vert='''
-267 -948 新宝島(わぃ村)
-267 -148
-226 -137
-226 -22 ｼｮｷｽﾎﾟｰﾝ
-226 69
-413 256
-413 1275 雪越
-413 1903 臨海技研
'''

[[line]]
name='常夏線'
color='#da4'
vert='''
530 -1043 天上高原
530 -1032
254 -756
254 1802 蓮窪
'''

[[line]]
name='SR新宝島線'
color='#38b'
vert='''
-2545 -982 よみの駅
-2445 -982
-2420 -957
-2420 -936
-2409 -925
-297 -925 新宝島(わぃ村)
-143 -925 二俣新町(わぃ村)
-77 -925 未定S1
6 -925
31 -950
31 -953
48 -970
91 -970 未定S2
133 -970
158 -955
159 -955
189 -1025
190 -1025
215 -1050
530 -1050
848 -1050
855 -1046
856 -1046
861 -1041
861 -1040
862 -1039
862 -1038
863 -1037
863 -1036
864 -1035
864 -1034
865 -1033
865 -1001
890 -976
890 -975
915 -950
928 -950
953 -925
954 -925
968 -911
968 -876
974 -870
991 -870
1006 -855
1026 -855
1035 -846
1039 -846
1051 -834
1051 -831
1070 -812
1092 -812
1096 -808
1164 -808
1189 -833
1198 -833
1203 -838
1209 -838
1213 -842
1213 -850
1220 -857
1220 -888
1224 -892
1365 -892
1381 -876
1381 -745 もじゃ村
'''

[[line]]
name='SR常磐線'
color='#338'
vert='''
-192 19 魚津
-160 19
-139 -2
-139 -896
-114 -921
-77 -921 未定J1
-5 -921
10 -936
10 -1123
35 -1148
35 -1149
59 -1173
202 -1173
'''

[[line]]
name='SR中央本線'
color='#c51'
vert='''
-297 -921 新宝島(わぃ村)
-168 -921
-143 -896
-143 -4
-152 5
-174 5 魚津
-239 5
-264 30
-265 30
-290 55
-291 55
-316 80
-317 80
-342 105
-343 105
-348 110
-361 110 雪ノ村
-327 110
-397 135
-398 135
-412 149
-412 760
-420 768
-420 792 スケタウン
-420 1308 雪越
-420 3992 永海
'''
